In [ ]:

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap
import matplotlib.patches as mpatches
import seaborn as sb

from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error
from sklearn import tree
import xgboost as xgb

In [ ]:
df_frio_frio_train = pd.read_csv('/content/drive/MyDrive/Organización de Datos/Tp 2/Datos/Train_TP2_Datos_2020-2C.csv')
df_frio_frio_train = df_frio_frio_train.fillna(0)
df_frio_frio_train.head()

ID    Region  ...        Stage       Prod_Category_A
0  27761      EMEA  ...  Closed Lost  Prod_Category_A_None
1  27760      EMEA  ...   Closed Won  Prod_Category_A_None
2  27446  Americas  ...   Closed Won  Prod_Category_A_None
3  16808  Americas  ...  Closed Lost  Prod_Category_A_None
4  16805  Americas  ...  Closed Lost  Prod_Category_A_None

[5 rows x 52 columns]

In [ ]:
train = df_frio_frio_train[((df_frio_frio_train['Stage'] == 'Closed Won') | (df_frio_frio_train['Stage'] == 'Closed Lost'))]
train['Stage'] = train['Stage'].apply(lambda x: 1 if x == 'Closed Won' else 0)
train

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


ID    Region  ... Stage       Prod_Category_A
0      27761      EMEA  ...     0  Prod_Category_A_None
1      27760      EMEA  ...     1  Prod_Category_A_None
2      27446  Americas  ...     1  Prod_Category_A_None
3      16808  Americas  ...     0  Prod_Category_A_None
4      16805  Americas  ...     0  Prod_Category_A_None
...      ...       ...  ...   ...                   ...
16942   8781      EMEA  ...     1  Prod_Category_A_None
16943   8786      EMEA  ...     1  Prod_Category_A_None
16944   8792      EMEA  ...     1  Prod_Category_A_None
16945  28561  Americas  ...     0  Prod_Category_A_None
16946  28318  Americas  ...     0  Prod_Category_A_None

[16883 rows x 52 columns]

### De momento solo trabajo con valores numericos

In [ ]:
train = train.select_dtypes(exclude=['object'])
train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 16883 entries, 0 to 16946
Data columns (total 14 columns):
 #   Column                              Non-Null Count  Dtype  
---  ------                              --------------  -----  
 0   ID                                  16883 non-null  int64  
 1   Pricing, Delivery_Terms_Quote_Appr  16883 non-null  int64  
 2   Pricing, Delivery_Terms_Approved    16883 non-null  int64  
 3   Bureaucratic_Code_0_Approval        16883 non-null  int64  
 4   Bureaucratic_Code_0_Approved        16883 non-null  int64  
 5   Submitted_for_Approval              16883 non-null  int64  
 6   Opportunity_ID                      16883 non-null  int64  
 7   ASP                                 16883 non-null  float64
 8   ASP_(converted)                     16883 non-null  float64
 9   Delivery_Year                       16883 non-null  int64  
 10  TRF                                 16883 non-null  int64  
 11  Total_Amount                        16883

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = \
    train_test_split(train.drop(columns = 'Stage'), train['Stage'], test_size=0.2, random_state=123)



In [ ]:
rf_model = RandomForestRegressor(random_state=1)
rf_model.fit(X_train, y_train)
preds = rf_model.predict(X_test)
rmse = np.sqrt(mean_squared_error(y_test, preds))
print("RMSE: %f" % (rmse))

RMSE: 0.304329


In [ ]:
# Gini importance
rf_model.feature_importances_

array([0.24110993, 0.00512213, 0.05236612, 0.01457772, 0.00551565,
       0.        , 0.12041847, 0.07560899, 0.06590688, 0.01876476,
       0.18313873, 0.10029407, 0.11717653])

In [ ]:
df_frio_frio_test = pd.read_csv('/content/drive/MyDrive/Organización de Datos/Tp 2/Datos/Test_TP2_Datos_2020-2C.csv')
df_frio_frio_test = df_frio_frio_test.dropna()
val_X = df_frio_frio_test.select_dtypes(exclude=['object'])

In [ ]:
predicts = rf_model.predict(val_X)
predicts

array([0.4 , 0.55, 0.37, ..., 0.74, 0.62, 0.28])

In [ ]:
output = pd.DataFrame({'Opportunity_ID':val_X.Opportunity_ID, 'Target': predicts})
output

Opportunity_ID  Target
0              10689    0.40
1              10689    0.55
2              10689    0.37
3              10690    0.10
4              10690    0.44
...              ...     ...
2546           12364    0.73
2547           12365    0.87
2548           12366    0.74
2549           12367    0.62
2550           12368    0.28

[2467 rows x 2 columns]

In [ ]:

final=output.groupby('Opportunity_ID').mean()
final


Target
Opportunity_ID          
10689           0.440000
10690           0.438000
10691           0.710000
10692           0.683333
10693           0.970000
...                  ...
12364           0.705000
12365           0.870000
12366           0.740000
12367           0.620000
12368           0.280000

[1567 rows x 1 columns]

In [ ]:
final.to_csv('/content/drive/MyDrive/Organización de Datos/Tp 2/Resultados/RandomForestScore1.csv')

##Ahora hago el GroupBy antes de entrenar

In [ ]:
train2 = df_frio_frio_train[((df_frio_frio_train['Stage'] == 'Closed Won') | (df_frio_frio_train['Stage'] == 'Closed Lost'))]
train2['Stage'] = train2['Stage'].apply(lambda x: 1 if x == 'Closed Won' else 0)
train2 = train2.drop_duplicates('Opportunity_ID')
train2 = train2.select_dtypes(exclude=['object'])
train2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9791 entries, 0 to 16946
Data columns (total 14 columns):
 #   Column                              Non-Null Count  Dtype  
---  ------                              --------------  -----  
 0   ID                                  9791 non-null   int64  
 1   Pricing, Delivery_Terms_Quote_Appr  9791 non-null   int64  
 2   Pricing, Delivery_Terms_Approved    9791 non-null   int64  
 3   Bureaucratic_Code_0_Approval        9791 non-null   int64  
 4   Bureaucratic_Code_0_Approved        9791 non-null   int64  
 5   Submitted_for_Approval              9791 non-null   int64  
 6   Opportunity_ID                      9791 non-null   int64  
 7   ASP                                 9791 non-null   float64
 8   ASP_(converted)                     9791 non-null   float64
 9   Delivery_Year                       9791 non-null   int64  
 10  TRF                                 9791 non-null   int64  
 11  Total_Amount                        9791 n

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [ ]:
train2

ID    Region  ... Stage       Prod_Category_A
0      27761      EMEA  ...     0  Prod_Category_A_None
1      27760      EMEA  ...     1  Prod_Category_A_None
2      27446  Americas  ...     1  Prod_Category_A_None
3      16808  Americas  ...     0  Prod_Category_A_None
4      16805  Americas  ...     0  Prod_Category_A_None
...      ...       ...  ...   ...                   ...
16942   8781      EMEA  ...     1  Prod_Category_A_None
16943   8786      EMEA  ...     1  Prod_Category_A_None
16944   8792      EMEA  ...     1  Prod_Category_A_None
16945  28561  Americas  ...     0  Prod_Category_A_None
16946  28318  Americas  ...     0  Prod_Category_A_None

[16883 rows x 52 columns]

In [ ]:
X_train, X_test, y_train, y_test = \
    train_test_split(train2.drop(columns = 'Stage'), train2['Stage'], test_size=0.2, random_state=123)

In [ ]:
rf_model2 = RandomForestRegressor(random_state=1)
rf_model2.fit(X_train, y_train)
preds = rf_model2.predict(X_test)
rmse = np.sqrt(mean_squared_error(y_test, preds))
print("RMSE: %f" % (rmse))

RMSE: 0.372077


In [ ]:
val_X2 = df_frio_frio_test.drop_duplicates('Opportunity_ID').select_dtypes(exclude=['object'])

predicts2 = rf_model2.predict(val_X2)
predicts2


array([0.5 , 0.2 , 0.74, ..., 0.52, 0.42, 0.27])

In [ ]:
output2 = pd.DataFrame({'Opportunity_ID':val_X2.Opportunity_ID, 'Target': predicts2})
output2

Opportunity_ID  Target
0              10689    0.50
3              10690    0.20
8              10691    0.74
9              10692    0.66
15             10693    0.84
...              ...     ...
2545           12364    0.67
2547           12365    0.84
2548           12366    0.52
2549           12367    0.42
2550           12368    0.27

[1567 rows x 2 columns]

In [ ]:
output2.groupby('Opportunity_ID').mean().to_csv('/content/drive/MyDrive/Organización de Datos/Tp 2/Resultados/RandomForestScore2.csv')

In [ ]:
final.reset_index()

Opportunity_ID    Target
0              10689  0.440000
1              10690  0.438000
2              10691  0.710000
3              10692  0.683333
4              10693  0.970000
...              ...       ...
1562           12364  0.705000
1563           12365  0.870000
1564           12366  0.740000
1565           12367  0.620000
1566           12368  0.280000

[1567 rows x 2 columns]

## Ahora voy a tratar de utilizar las variables categoricas
